#embeddeb server container depedencies
server:
  port: 8082


token:
  secret_key: sdvsdvsdvkbkjsdkvksdvksdvksdbvkbsdkvbdkv
  validity_period: 20000000

#application specfic dependency
spring:
  application:
    name: IMDB-CLONE-API-GATEWAY
  cloud:
    gateway: 
      enabled: true
      default-filters:
      - AddRequestHeader=gateway-key, ${gateway.key}
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Max-Age
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
              allowedOrigins: 
              - "*"
              allowedMethods: "*"
              allowedHeaders: "*"
              exposedHeaders: "*"
              allowCredentials: false
              maxAge: 20000
      httpclient:
        connect-timeout: 30000
        response-timeout: 20s
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: AUTH-ROUTE
        predicates:
        - Path=/auth/{segment}
        - Method=POST
        filters:
        - name: RequestSize
          args:
            maxSize: 200KB
        - SetPath=/user/account/{segment}
        uri: lb://imdb-clone-userservice
      - id: MANAGMENT-ROUTE
        predicates:
        - Path=/user/followrequest
        - Method=POST
        - Query=target_user_id
        filters:
        - CustomTokenValidationFilterFactory
        - name: RequestSize
          args:
            maxSize: 1KB
        - SetPath=/user/managment/followrequest
        uri: lb://imdb-clone-userservice

          
discovery:
  server:
    username: aaaaaaaaaaaa
    password: bbbbbbbbbbb

gateway:
  key: mygatewaykey

#eureka registry client and instance configuration
eureka: 
  instance:
    healthCheckUrlPath: /myhealth
    statusPageUrlPath: /myinfo
    securePortEnabled: false
    nonSecurePortEnabled: true
    instance-id: ${spring.application.name}:${random.value}:${server.port}
    lease-renewal-interval-in-seconds: 28
  client:
    refresh:
      enable: true
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${discovery.server.username}:${discovery.server.password}@localhost:8081/eureka/
  

