#embeddeb server container depedencies
server:
  port: 8082


token:
  secret_key: sdvsdvsdvkbkjsdkvksdvksdvksdbvkbsdkvbdkv
  validity_period: 20000000

#application specfic dependency
spring:
  application:
    name: IMDB-CLONE-API-GATEWAY
  cloud:
    gateway: 
      enabled: true
      default-filters:
      - AddRequestHeader=gateway-key, ${gateway.key}
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Max-Age
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
              allowedOrigins: 
              - "*"
              allowedMethods: "*"
              allowedHeaders: "*"
              exposedHeaders: "*"
              allowCredentials: false
              maxAge: 20000
      httpclient:
        connect-timeout: 30000
        response-timeout: 20s
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: AUTH-ROUTE
        predicates:
        - Path=/auth/{segment}
        - Method=POST
        filters:
        - name: RequestSize
          args:
            maxSize: 200KB
        - SetPath=/user/account/{segment}
        uri: lb://imdb-clone-userservice
      - id: MANAGMENT-ROUTE
        predicates:
        - Path=/user/followrequest
        - Method=PUT
        - Query=targetUserId
        filters:
        - CustomTokenValidationFilterFactory
        - name: RequestSize
          args:
            maxSize: 1KB
        - SetPath=/user/managment/followrequest
        uri: lb://imdb-clone-userservice
      - id: MOVIE-UPLOAD-ROUTE
        predicates:
        - Path=/movie/upload
        - Method=POST
        filters:
        - CustomTokenValidationFilterFactory
        - CustomAdminRoleVerificationFactory
        - name: RequestSize
          args:
            maxSize: 230MB
        - SetPath=/movie/managment/upload
        uri: lb://imdb-clone-movieservice
      - id: MOVIE-INFO-ROUTE
        predicates:
        - Path=/movie/info
        - Method=GET
        - Query=movieId
        filters:
        - CustomHeaderPopulateFilterFactory
        - SetPath=/movie/fetch/info
        uri: lb://imdb-clone-movieservice
      - id: REVIEW-ROUTE
        predicates:
        - Path=/movie/review
        - Method=GET
        - Query=movieId
        - Query=pageId
        filters:
        - CustomHeaderPopulateFilterFactory
        - SetPath=/movie/fetch/review
        uri: lb://imdb-clone-movieservice
      - id: REPLY-ROUTE
        predicates:
        - Path=/movie/reply
        - Method=GET
        - Query=reviewId
        - Query=pageId
        filters:
        - CustomHeaderPopulateFilterFactory
        - SetPath=/movie/fetch/reply
        uri: lb://imdb-clone-movieservice
      - id: SINGLE-REVIEW-ROUTE
        predicates:
        - Path=/movie/review
        - Method=GET
        - Query=reviewId
        filters:
        - CustomHeaderPopulateFilterFactory
        - SetPath=/movie/fetch/review
        uri: lb://imdb-clone-movieservice
      - id: SINGLE-REPLY-ROUTE
        predicates:
        - Path=/movie/reply
        - Method=GET
        - Query=replyId
        filters:
        - CustomHeaderPopulateFilterFactory
        - SetPath=/movie/fetch/reply
        uri: lb://imdb-clone-movieservice
      - id: REVIEW-UPLOAD-ROUTE
        predicates:
        - Path=/movie/review
        - Method=POST
        - Query=movieId
        filters:
        - CustomTokenValidationFilterFactory
        - name: RequestSize
          args:
            maxSize: 2KB
        - SetPath=/movie/managment/review
        uri: lb://imdb-clone-movieservice
      - id: REPLY-UPLOAD-ROUTE
        predicates:
        - Path=/movie/reply
        - Method=POST
        - Query=reviewId
        filters:
        - CustomTokenValidationFilterFactory
        - name: RequestSize
          args:
            maxSize: 2KB
        - SetPath=/movie/managment/reply
        uri: lb://imdb-clone-movieservice
      - id: REVIEW-REACT-ROUTE
        predicates:
        - Path=/movie/review/react
        - Method=PUT
        - Query=reviewId
        filters:
        - CustomTokenValidationFilterFactory
        - SetPath=/movie/managment/review/react
        uri: lb://imdb-clone-movieservice
      - id: REPLY-REACT-ROUTE
        predicates:
        - Path=/movie/reply/react
        - Method=PUT
        - Query=replyId
        filters:
        - CustomTokenValidationFilterFactory
        - SetPath=/movie/managment/reply/react
        uri: lb://imdb-clone-movieservice
      - id: RATING-UPLOAD-ROUTE
        predicates:
        - Path=/movie/rating
        - Method=PUT
        - Query=movieId
        filters:
        - CustomTokenValidationFilterFactory
        - name: RequestSize
          args:
            maxSize: 2KB
        - SetPath=/movie/managment/rating
        uri: lb://imdb-clone-movieservice
      - id: WISHLIST-UPDATE-ROUTE
        predicates:
        - Path=/user/wishlist
        - Method=PUT
        - Query=movieId
        filters:
        - CustomTokenValidationFilterFactory
        - SetPath=/user/managment/wishlist
        uri: lb://imdb-clone-userservice
      - id: WATCHLIST-UPDATE-ROUTE
        predicates:
        - Path=/user/watchlist
        - Method=PUT
        - Query=movieId
        filters:
        - CustomTokenValidationFilterFactory
        - SetPath=/user/managment/watchlist
        uri: lb://imdb-clone-userservice
      - id: WISHLIST-ROUTE
        predicates:
        - Path=/user/wishlist
        - Method=GET
        - Query=userId
        - Query=pageId
        filters:
        - CustomHeaderPopulateFilterFactory
        - SetPath=/user/data/wishlist
        uri: lb://imdb-clone-userservice
      - id: WATCHLIST-ROUTE
        predicates:
        - Path=/user/watchlist
        - Method=GET
        - Query=userId
        - Query=pageId
        filters:
        - CustomHeaderPopulateFilterFactory
        - SetPath=/user/data/watchlist
        uri: lb://imdb-clone-userservice
      - id: RATINGLIST-ROUTE
        predicates:
        - Path=/user/ratinglist
        - Method=GET
        - Query=userId
        - Query=pageId
        filters:
        - CustomHeaderPopulateFilterFactory
        - SetPath=/user/data/ratinglist
        uri: lb://imdb-clone-userservice
      
          
discovery:
  server:
    username: aaaaaaaaaaaa
    password: bbbbbbbbbbb

gateway:
  key: mygatewaykey

#eureka registry client and instance configuration
eureka: 
  instance:
    healthCheckUrlPath: /myhealth
    statusPageUrlPath: /myinfo
    securePortEnabled: false
    nonSecurePortEnabled: true
    instance-id: ${spring.application.name}:${random.value}:${server.port}
    lease-renewal-interval-in-seconds: 28
  client:
    refresh:
      enable: true
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${discovery.server.username}:${discovery.server.password}@localhost:8081/eureka/
  

