
server:
  port: 0
  

discovery:
  server:
    username: aaaaaaaaaaaa
    password: bbbbbbbbbbb
  
spring:
  application:
    name: IMDB-CLONE-MOVIESERVICE
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10KB
      max-file-size: 230MB
      max-request-size: 260MB



gateway:
  key: mygatewaykey
    
user:
  key: myuserkey
     
eureka: 
  instance:
    healthCheckUrlPath: /myhealth
    statusPageUrlPath: /myinfo
    securePortEnabled: false
    nonSecurePortEnabled: true
    instance-id: ${spring.application.name}:${random.value}:${server.port}
    lease-renewal-interval-in-seconds: 28
  client:
    refresh:
      enable: true
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${discovery.server.username}:${discovery.server.password}@localhost:8081/eureka/
  
